### PR TITLE
Adding script_job resource

### PR DESCRIPTION
**Pull request by tomsiouan**
### Working
 - Creation
 - Reading

### Known Issues
 - Naming jobs during creation: It is currently not possible to assign a proper name to a job during creation because the SimpleMDM API does not support this feature. The API just give automatically the following name : "API Job"
 - Job scheduling: The API does not allow jobs to be scheduled for execution at this time.
 - Deleting a script job: Deleting a job is not applicable since the resource does not really exist in the SimpleMDM API. While the API mentions that jobs can be canceled, scheduling them is not yet implemented.

### Other
Update is note supported, the API doesn't allow us to do this.

### Next Step
I will contact SimpleMDM support to request the implementation of these features.

### CODE REVIEW

**Comment by DavidKrau** [comment]
Hey Tom, i will review it in next few days.

**Comment by tomsiouan** [comment]
It's better with documentation.

**Comment by DavidKrau** [comment]
Hey Tom, 

I fixed few issues and will release new provider with script jobs today.

**Comment by tomsiouan** [comment]
Hey David,

I messed up few issues. Thanks for your review. When the SimpleMDM team will add what is missing, I will add it to the TF provider.

**Pull request merged**
